services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm run db:migrate && npm run dev"
